"""add_user_id_to_sessions

Revision ID: b6c940de6ee9
Revises: 5bfe85165a56
Create Date: 2025-10-20 12:50:22.261010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c940de6ee9'
down_revision: Union[str, Sequence[str], None] = '5bfe85165a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'user_id')
    # ### end Alembic commands ###
